EWAR sitrep template
R4EPI/sitrep pull request #320
Opened 2023-02-20 20:03 UTC by pbkeating

This template provides a short EWAR/EBS analysis report and requires the updates to the epidict package to create a fake dataset

2023-02-27 16:38 UTC, pbkeating commented
Think I will leave this as it is. It could be shortened by creating a function for the maps of events, alerts and responses, but cuts like 100 lines of code out of 1400 and so impact is not that great

2023-10-16 09:35 UTC, pbkeating commented
Anyone can have a look at this? Been here waiting a review for quite some time now.

2023-10-16 16:58 UTC, aspina7 commented
Will need to be included as part of next contract @nsbatra

2025-03-05 15:08 UTC, aspina7 requested changes
thx pat couple comments here too

2025-03-06 03:50 UTC, pbkeating commented
> thx pat couple comments here too

Quick question, were all the commits I made included as part of this review? I'm wondering now if I did a pull request with those additional edits

2025-03-06 06:08 UTC, pbkeating commented
I think I should have addressed all the feedback on this here

2025-03-06 06:17 UTC, aspina7 commented
> Quick question, were all the commits I made in February included as part of this review? I'm wondering now if I did a pull request with those additional edits

there were two commits from february - which I reviewed, not sure if that is everything you wanted to push?

2025-03-06 06:23 UTC, pbkeating commented
Looks like it’s all good. The ones from February were the ones I was talking about and somebody is up early!
P

Patrick Keating (he/him)
Epidemiology Advisor for Bangladesh, Ethiopia, India, South Sudan and Malaysia
Doctors Without Borders/Médecins Sans Frontières  (MSF UK)
Level 5, Artesian, 9 Prescot Street, London E1 8AZ
Whatsapp: +447871642307

Learn more about Applying Epidemiology in Humanitarian contexts on this Tembo course https://tembo.msf.org/course/view.php?id=3866

Find surveillance-related resources in the Surveillance toolkit<https://msfintl.sharepoint.com/:f:/s/OCA-dept-PHD/ElW2YbccjwxBniRuzHewBCYBAZ0ZpuWs7hI6ZeHMhv8DfA?e=Twz68W>

Find outbreak-related resources in the https://msfintl.sharepoint.com/sites/OCA-dept-PHD/SitePages/OMT-Page.aspx<https://msfintl.sharepoint.com/sites/OCA-dept-PHD/SitePages/OMT-Page.aspx#outbreak-reporting>


From: Alex Spina ***@***.***>
Sent: 06 March 2025 12:18
To: R4EPI/sitrep ***@***.***>
Cc: Patrick Keating ***@***.***>; Author ***@***.***>
Subject: Re: [R4EPI/sitrep] EWAR sitrep template (PR #320)


CAUTION: This email originated from outside MSF. Do not click links, open attachments or provide information unless you recognise the sender and know that the content is safe..

________________________________

Quick question, were all the commits I made in February included as part of this review? I'm wondering now if I did a pull request with those additional edits

there were two commits from february - which I reviewed, not sure if that is everything you wanted to push?

—
Reply to this email directly, view it on GitHub<https://github.com/R4EPI/sitrep/pull/320#issuecomment-2702914006>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AE2NEQYMKNEBET4S6YZZBRD2S7R77AVCNFSM6AAAAABREZC6X6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDOMBSHEYTIMBQGY>.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[Image removed by sender. aspina7]aspina7 left a comment (R4EPI/sitrep#320)<https://github.com/R4EPI/sitrep/pull/320#issuecomment-2702914006>

Quick question, were all the commits I made in February included as part of this review? I'm wondering now if I did a pull request with those additional edits

there were two commits from february - which I reviewed, not sure if that is everything you wanted to push?

—
Reply to this email directly, view it on GitHub<https://github.com/R4EPI/sitrep/pull/320#issuecomment-2702914006>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AE2NEQYMKNEBET4S6YZZBRD2S7R77AVCNFSM6AAAAABREZC6X6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDOMBSHEYTIMBQGY>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2025-03-06 09:25 UTC, merged